### ISSUE TITLE
Divide by zero

### ISSUE THREAD

**Issue by cyriltasse** [ratt-ru/PyMORESANE#20]
I often see this error message being displayed

`iuwt_toolbox.py:254: RuntimeWarning: divide by zero encountered in double_scalars out1 = 20*(np.log10(np.linalg.norm(in1)/np.linalg.norm(in1-in2)))`

While the results "looks" all right (I mean no NaN or infinites etc). Have you encountered this before? Any fix?

**Comment by JSKenyon** [comment]
Does it seem to line up with the first iteration? I may be mistaken, but I suspect it happens when the one of of the inputs is not properly populated yet. I also think that the code behaves correctly - I just never put in the logic to suppress the warning. You could add the following around the call in question.
```
with np.errstate(divide='ignore'): 
    # some code here
```

**Comment by cyriltasse** [comment]
Thanks, I'll let you know if NaNs show up at some point...
