### ISSUE TITLE
Updating PyMORESANE: Is the line search worth the cost?

### ISSUE THREAD

**Issue by JSKenyon** [ratt-ru/PyMORESANE#3]
Just setting this issue up so that we can discuss the pros and cons of this change. 

Have been chatting to @arwina about this but I am hesitant to do it if the additional computational cost does not buy substantially improved results. 

@o-smirnov suggested that perhaps some additional tests can be run using the MATLAB version.

To explain my concern, the line search is an iterative procedure which entails a convolution, a wavelet decompostion and an SNR evaluation. All of these come at a rather substantial computational cost, particularly for large data sets. In particular, even the GPU implementation of the wavelet transform will be relatively inefficient due to the necessity of copying data back and forth over and over again. 

I would suggest running the MATLAB version with and without the line search. The data of interest would be total run time in both cases, as well the number of iterations requred before convergence for every minor loop. If the iterations are decreased, then the computational cost may be offset. Otherwise, the problem may require more thought.

**Comment by sphemakh** [comment]
If you can get it to work that would be really cool. Optimising it is a second order issue I think.

**Comment by o-smirnov** [comment]
I think the question is @SpheMakh , is this particular improvement worth porting to Python? This will come up every time @arwina adds feature X to the MATLAB version of MORESANE. We've agreed that @JSKenyon will continue supporting the Python version to the best of his ability, and porting over small improvements will not be a problem.

The question is, how do we deal with more substantial changes such as this one? It looks to add complexity the algorithm, so I agree with @JSKenyon , it would be good to see some analysis of its performance in the MATLAB version. 

I think going forward we should treat the MATLAB codebase as "experimental", where new features are tried out and tested, since @arwina can do this quickly. Once they're proven, we port them to PyMORESANE. So, do we consider line search to be a proven feature -- @arwina, could you post some comments on this here?

@chiaraf , what do you think?

**Comment by chiaraf** [comment]
We are writing together me and @arwina. Her last modifications were added to address the concerns about the stability of the conjugate gradient expressed by the referee. Indeed the algorithm is now heavier from the computation point of view, but with more reliable stopping criteria. 

If in terms of reliability of stopping criteria it's an improvement and it's mathematically more correct, the quality of the recovery won't be necessarily very different. Based on the tests that she did while writing the paper, we do not expect significantly different results. Unfortunately she has not the time now to do more quantitative comparisons (PhD manuscript to finish soon).

More work can be done to search for more sophisticated and faster minimisation criteria. It cannot be done now by @arwina (and I do not know later on, depending on what she will work on). It is probably worth to invite David too in this discussion? (since his new student is starting working on MORESANE)

**Comment by o-smirnov** [comment]
Agreed, I've emailed them to get their github IDs.

OK, sounds like line search is not a crucial improvement at present, so perhaps we can keep it on hold for now. In any case this is a good discussion to continue!

**Comment by arwina** [comment]
Adding the line search feature to PyMoresane is not very complicated. I would suggest  to consider it in the algorithm and let the user choose whether to use it or not, by specifying that is slower.  If not, I suggest to add a comment on PyMoresane so that user wont be surprised to see the difference compared to the algorithm described in the Paper.

**Comment by davidmary** [comment]
Hi all

I would say that Oleg's and Arwa's suggestions are fine accounting for the hecticity of current times.
Finding local manpower to continue developing Moresane is an issue that we still discussed deeply this morning with Chiara, Andre and the Lab director. So not fixed yet but in progress.

As for Jeremie, his advisor is Andre. I am not sure what's Andre's plan regarding the precise topics of Jeremie's master's thesis. Developing Moresane was a possible research axis Andre had in mind at the beginning for Jeremie and we discussed a bit on this. Recently however Andre has progressed a lot with a postdoctoral student on another approach.  So the best is to ask him !

**Comment by JSKenyon** [comment]
Thank you everyone for your contributions. As @arwina suggested, it is possible to add it as an optional extra step. I will take that approach for now. I don't have a specific timeline for this improvement though.

**Comment by JSKenyon** [comment]
I have implemented a rudimentary version of the change. As expected, there is a substantial increase in computational cost. Approximate processing time for a 512x512 image has increased from 2 minutes to around 17 minutes for a low accuracy run and around 40 minutes for a high accuracy run.

@arwina, did you experience a similar increase in processing time, or do you feel I have made an error?

**Comment by arwina** [comment]
@JSKenyon it indeed takes more time (around 15mn with matlab but  i should recheck), of course it depends on the adopted parameters;  an  accuracy of  0.005-0.01 in the golden algorithm should be ok. You can always choose to impose  the line search only when the SNR decreases.

**Comment by JSKenyon** [comment]
I have noticed that the golden section search often doesn't improve the SNR very much after a few iterations. @arwina, do you think it would be worth checking the improvement in SNR as an additional stopping criteria for the search? That way we could minimise the number of iterations used. I think this may work, as the golden section search converges reliably so there are no "jump" problems; once in the neighbourhood of the maximum it stays there.

**Comment by JSKenyon** [comment]
Closing for now, though I am still considering this.
