### ISSUE TITLE
odd results with negative components

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/PyMORESANE#9]
I'm getting some odd results with CygA images when I make it deal with negative flux. This seems to deconvolve a lot worse than positive ones, even though I'm not enforcing positivity. Why the assymetry?

(Need to deal with negative flux for polarization maps, and also for residual maps where an LSM component is over-subtracted.)

I've left an MS and some images on `/net/aretha/home/oms/VLA-CygA/MS-Jon`. The LO-POL images were made with WSCLEAN and MORESANE as (note latest build of wsclean on aretha, better use that):

```
/home/oms/src/wsclean-code/wsclean/build/wsclean -niter 3 -scale 0.000111111111111 -superweight 4 -weight briggs -0.50 -moresane-arg '-sl 3 -sbr 512' -channelrange 128 192 -datacolumn DATA -name reduction-26Jun15/plots-CYG-S-LO-POL-160-64/CYG-S-LO-POL-spw0-s0-init-wsclean -field 2 -pol IQUV -gain 0.05 -moresane-ext /home/oms/PyMORESANE/pymoresane/bin/runsane -threshold 0.027 -nosmallinversion -size 1024 1024 -mgain 0.85 CYG-S-LO-POL.MS
```

The LO2-POL images were made with normal wsclean using

```
/home/oms/src/wsclean-code/wsclean/build/wsclean -niter 100000 -scale 0.000111111111111 -superweight 4 -weight briggs -0.50 -channelrange 128 192 -datacolumn DATA -name reduction-26Jun15/plots-CYG-S-LO2-POL-160-64/CYG-S-LO2-POL-spw0-s0-init-wsclean -field 2 -pol IQUV -gain 0.05 -threshold 0.045 -nosmallinversion -size 1024 1024 -mgain 0.85 CYG-S-LO2-POL.M
```

What worries me is the deep large "hole" in the Q residual from MORESANE, which doesn't show up in the normal CLEAN residuals.

I've seen similar holes using MORESANE on I maps with negative flux, will post a separate issue about this later.

**Comment by JSKenyon** [comment]
Improved in the latest release. Closing for now.

**Comment by o-smirnov** [comment]
Reopening this. Definitely looking better in polarization now, however there's still a negative hole left in the Stokes I residuals which I feel should really have been absorbed into the model. Could you check what's going on? Have made a new copy of the MS in the same directory, `/net/aretha/home/oms/VLA-CygA/MS-Jon`, and added some images to illustrate. Command is

```
/home/oms/src/wsclean-code/wsclean/build/wsclean -niter 3 -scale 0.000111111111111 -superweight 4 -weight briggs -0.50 -moresane-arg '-aog -sl 3 -sbr 512' -channelrange 96 224 -datacolumn CORRECTED_DATA -name CYG-S-LO-s11.moresane -field 2 -pol IQUV -gain 0.05 --moresane-ext /home/oms/PyMORESANE/pymoresane/bin/runsane -threshold 0.085 -nosmallinversion -size 1024 1024 -mgain 0.85 CYG-S-LO.MS
```

**Comment by JSKenyon** [comment]
I will give the problem some thought. If I am honest, a quick and easy solution may not be possible. The original MORESANE framework was done assuming that the sky was strictly positive so the object extraction strategy probably fails for negative objects. I imagine that I could improve PyMORESANE if I reimplemented it from scratch, now that I understand it substantially better. Is that something which you feel would be interesting/necessary?

**Comment by o-smirnov** [comment]
It would, but not if you have to re-implement everything from scratch. So let's figure out what's going on first, it could well be minor still. Or it could be something pathological with this data (we're pretty far down the rabbit hole here), maybe things diverge quickly. Could you check if it tries to do something about the big negative hole in particular?

What might be nice is better diagnostic output from PyMORESANE (or having it controlled via a --verbosity LEVEL option.) The present bunch of messages is not very informative.

**Comment by JSKenyon** [comment]
Reimplement from scratch is likely a bit of an exaggeration. All my utility functions are pretty good. So the decompositions etc will be fine. The bigger issue lurks in the main body of the code. It is somewhat convoluted and could do with a rewrite. Though it will take some time. 

I will try and take a look at the specifics of this case. I suspect that even with the new thresholding procedure, there are false detections which dig holes in the residual. The first time I attempted to use PyMORESANE on the Cyg A data (ages ago now), I also had those negative holes and they were appearing in the residual almost immediately. This sort of supports my "false positive" theory. Admittedly, it is only a theory.

**Comment by o-smirnov** [comment]
Interesting data point: regular WSCLEAN does a lot better with this. 

```
/home/oms/src/wsclean-code/wsclean/build/wsclean -niter 100000 -scale 0.000111111111111 -superweight 4 -weight briggs -0.50 -channelrange 96 224 -datacolumn CORRECTED_DATA -name CYG-S-LO-s12-clean.clean -field 2 -pol IQUV -gain 0.05 -threshold 0.005 -nosmallinversion -size 2048 2048 -mgain 0.85 CYG-S-LO.MS
```

**Comment by o-smirnov** [comment]
P.S. If we've found an edge case where MORESANE does worse than CLEAN, and that can't be fixed without major rework of the algorithm, then that's also a valid answer. But we need to establish this a bit more definitely. Also in order to know where to use MORESANE and where CSCLEAN, when we make pipelines!

**Comment by JSKenyon** [comment]
That is a very fair point. There are cases in which you expect CLEAN to be better. Admittedly, I do not believe this is one of them. :-P I am struggling to get the commands to run. Keep getting seg faults. The MS you use in the command is not the same one as in the MS-Jon folder though so I suspect it is just a parameter problem. Any suggestions?

**Comment by JSKenyon** [comment]
Ah, think I sorted it out. Copied the MS with the name you used in the command to my home on Jake and it seems to be running properly now.

**Comment by JSKenyon** [comment]
I have thought a little more about this problem. My current best working theory for why CLEAN outperforms MORESANE in this case is relatively simple providing we assume that the point sources have been over-subtracted.

Each iteration of CLEAN adds a single pixel to the model. The added pixel is not required to be positive. In the case of over-subtracted sources, CLEAN is free to add a single negative pixel at the location of the source which has a negative magnitude equal to the amount of over-subtraction. Thus, when convolved with the PSF and subtracted from the dirty map/visibilities, it essentially fills up the hole which in turn improves the residuals. 

MORESANE does not currently mimic this behaviour. Negative structures will not be identified at the object extraction step and will consequently not be modelled. The solution procedure may still add negative pixels but these will be near positive objects and will be placed in the model to compensate for overestimation. MORESANE will make no attempt to consider the effect of what would be a single negative pixel in the model.  

In order to fix this it would be necessary to allow MORESANE to consider both high correlation and high anti-correlation structures in the wavelets. I theorise that the solution procedure could then model the effects of over-subtraction properly. The biggest problem I can see with this is having to redefine the object extraction procedure.

I would appreciate any further insight into the problem and also whether you agree with me regarding CLEAN's advantage in this case.

**Comment by o-smirnov** [comment]
Yes that sounds like a very sensible explanation. @arwina, what do you think? Is it a simple tweak to the object extraction procedure to consider anti-correlations as well, and pick up negative objects?

Note that this is needed not just for modelling oversubtraction, but also for polarization which can be physically negative.

**Comment by JSKenyon** [comment]
My personal, less informed opinion is that tweaking the procedure is possible. I am uncertain whether or not it would have repercussions. Perhaps I can dedicate next week to exploring this idea a little.

**Comment by arwina** [comment]
I second what Jon explained; in my opinion this backward step of CLEAN (detecting neg components) is the main reason behind its success. 
I think tweaking can be done:  a first naive idea is to separate negative and positive wavelets and apply source extraction on both yet with the same threshold, so that only high negative 'sources' can be considered to avoid  detecting the neg psf sidelobes. Estimation is done jointly afterwords using all detected wavelets.

**Comment by arwina** [comment]
I ll give it a try on matlab and see how it works

**Comment by JSKenyon** [comment]
I have added an option to the latest release which turns on anti-correlation discovery in the source extraction step. It can be enabled using -nc or --negcomp. The feature is still experimental, but appears to give improved results. I am going to close this for now, though feel free to reopen it if the new mode does not work as expected.

**Comment by o-smirnov** [comment]
Preliminary indications are that --negcomp works spectacularly well. :)
